# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fNESCObEzAO7IvqJSpBz_4nnqDkZiRHe
"""

pip install PyPDF2 nltk wordcloud matplotlib

import PyPDF2
import nltk
from wordcloud import WordCloud
import matplotlib.pyplot as plt
from collections import Counter

file_path ="/content/utgan_kunlar_ziyouz_com.pdf"

with open(file_path, 'rb') as file:
    reader = PyPDF2.PdfReader(file)
    text =""

    for page in reader.pages:
        text += page.extract_text()

print("PDF dan olingan matn uzunligi:", len(text))

nltk.download('punkt')
nltk.download('punkt_tab')
tokens = nltk.word_tokenize(text.lower())

words = [w for w in tokens if w.isalpha()]

common = Counter(words).most_common(20)
print("\nEng ko'p ishlatiladigan so'zlar:")
print(common)

wc = WordCloud(width=800, height=400, background_color='white').generate(" ".join(words))

plt.figure(figsize=(10, 5))
plt.imshow(wc, interpolation='bilinear')
plt.axis("off")
plt.show()